CREATE TABLE IF NOT EXISTS atendees(
id INTEGER PRIMARY KEY AUTOINCREMENT,
event_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) on DELETE CASCADE,
FOREIGN KEY (event_id) REFERENCES events(id) on DELETE CASCADE
);